// <auto-generated />
using System;
using CelularesAPI.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelularesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241108003758_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CelularesAPI.Models.Celular.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Bateria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Camara")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pantalla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Procesador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdSistema");

                    b.ToTable("Celulares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Almacenamiento = "256GB",
                            Bateria = "4000 mAh",
                            Camara = "Triple, 50 megapíxeles",
                            FechaLanzamiento = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdMarca = 1,
                            IdSistema = 1,
                            Modelo = "Galaxy S24",
                            Pantalla = "6.2 pulgadas",
                            Precio = "$1.200.000",
                            Procesador = "Exynos 2400",
                            RAM = "8GB"
                        },
                        new
                        {
                            Id = 2,
                            Almacenamiento = "256GB",
                            Bateria = "4900 mAh",
                            Camara = "Triple, 50 megapíxeles",
                            FechaLanzamiento = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdMarca = 1,
                            IdSistema = 1,
                            Modelo = "Galaxy S24+",
                            Pantalla = "6.7 pulgadas",
                            Precio = "$1.500.000",
                            Procesador = "Exynos 1480",
                            RAM = "12GB"
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Color.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Onyx Black"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Marble Gray"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cobalt Violet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Amber Yellow"
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Color.ColoresCelular", b =>
                {
                    b.Property<int>("IdCelular")
                        .HasColumnType("int");

                    b.Property<int>("IdColor")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCelular", "IdColor");

                    b.HasIndex("IdColor");

                    b.ToTable("ColoresCelular");

                    b.HasData(
                        new
                        {
                            IdCelular = 1,
                            IdColor = 1,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193556-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 1,
                            IdColor = 2,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193565-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 1,
                            IdColor = 3,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193683-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 1,
                            IdColor = 4,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/195008-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 2,
                            IdColor = 1,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193692-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 2,
                            IdColor = 2,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193701-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 2,
                            IdColor = 3,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193710-800-auto?width=800&height=auto&aspect=true"
                        },
                        new
                        {
                            IdCelular = 2,
                            IdColor = 4,
                            UrlImagen = "https://samsungar.vtexassets.com/arquivos/ids/193719-800-auto?width=800&height=auto&aspect=true"
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Marca.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Apple"
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Rol.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Moderador"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Rol.RolUsuario", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("CelularesAPI.Models.Sistema.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sistemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Android",
                            Version = 14
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "iOS",
                            Version = 18
                        });
                });

            modelBuilder.Entity("CelularesAPI.Models.Usuario.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CelularesAPI.Models.Celular.Celular", b =>
                {
                    b.HasOne("CelularesAPI.Models.Marca.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelularesAPI.Models.Sistema.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("CelularesAPI.Models.Color.ColoresCelular", b =>
                {
                    b.HasOne("CelularesAPI.Models.Celular.Celular", null)
                        .WithMany()
                        .HasForeignKey("IdCelular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelularesAPI.Models.Color.Color", null)
                        .WithMany()
                        .HasForeignKey("IdColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CelularesAPI.Models.Rol.RolUsuario", b =>
                {
                    b.HasOne("CelularesAPI.Models.Rol.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelularesAPI.Models.Usuario.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
